// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SA.Infrastructure.Persistence;

#nullable disable

namespace SA.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SaDbContext))]
    [Migration("20260920140932_Alerts")]
    partial class Alerts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("SA.Domain.Entities.Alerts.AlertRule", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastTriggeredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Threshold")
                        .HasColumnType("REAL");

                    b.Property<int>("TriggerCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.HasIndex("UserId", "Code");

                    b.ToTable("AlertRule", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Alerts.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Capital.BillboardRecord", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double?>("BuyAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("ChangePercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("Close")
                        .HasColumnType("REAL");

                    b.Property<double?>("DealAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("Explain")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double?>("NetAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("Next10Change")
                        .HasColumnType("REAL");

                    b.Property<double?>("Next1Change")
                        .HasColumnType("REAL");

                    b.Property<double?>("Next5Change")
                        .HasColumnType("REAL");

                    b.Property<double?>("SellAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("TurnoverRate")
                        .HasColumnType("REAL");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code", "TradeDate", "Reason");

                    b.ToTable("BillboardRecord", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Capital.BlockTrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuyerName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Close")
                        .HasColumnType("REAL");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double?>("DealAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("DealPrice")
                        .HasColumnType("REAL");

                    b.Property<double?>("DealVolume")
                        .HasColumnType("REAL");

                    b.Property<double?>("PremiumRatio")
                        .HasColumnType("REAL");

                    b.Property<string>("SellerName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code", "TradeDate");

                    b.ToTable("BlockTrade", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Capital.FundFlowDaily", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ChangePercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("Close")
                        .HasColumnType("REAL");

                    b.Property<double>("LargeNet")
                        .HasColumnType("REAL");

                    b.Property<double>("MainNet")
                        .HasColumnType("REAL");

                    b.Property<double?>("MainRatio")
                        .HasColumnType("REAL");

                    b.Property<double>("MediumNet")
                        .HasColumnType("REAL");

                    b.Property<double>("SmallNet")
                        .HasColumnType("REAL");

                    b.Property<double>("SuperLargeNet")
                        .HasColumnType("REAL");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code", "Date");

                    b.ToTable("FundFlowDaily", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Capital.MarginDetail", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ChangePercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("Close")
                        .HasColumnType("REAL");

                    b.Property<double?>("FinanceBalance")
                        .HasColumnType("REAL");

                    b.Property<double?>("FinanceBalanceRatio")
                        .HasColumnType("REAL");

                    b.Property<double?>("FinanceBuy")
                        .HasColumnType("REAL");

                    b.Property<double?>("FinanceNetBuy")
                        .HasColumnType("REAL");

                    b.Property<double?>("LoanBalance")
                        .HasColumnType("REAL");

                    b.Property<double?>("LoanVolume")
                        .HasColumnType("REAL");

                    b.Property<double?>("TotalBalance")
                        .HasColumnType("REAL");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code", "Date");

                    b.ToTable("MarginDetail", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Capital.NorthboundHolding", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("HoldDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AddShares")
                        .HasColumnType("REAL");

                    b.Property<double?>("AddSharesAmp")
                        .HasColumnType("REAL");

                    b.Property<string>("DateType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double?>("FreeSharesRatio")
                        .HasColumnType("REAL");

                    b.Property<double?>("HoldMarketCap")
                        .HasColumnType("REAL");

                    b.Property<double?>("HoldShares")
                        .HasColumnType("REAL");

                    b.Property<string>("Industry")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrgQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PreviousHoldShares")
                        .HasColumnType("REAL");

                    b.Property<int?>("PreviousOrgQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TotalSharesRatio")
                        .HasColumnType("REAL");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code", "HoldDate");

                    b.ToTable("NorthboundHolding", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Collect.CollectTaskLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CostMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetryResult")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RowsWritten")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("CollectTaskLog", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Collect.DataSourceStatus", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Domains")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastOkAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("UptimePct")
                        .HasColumnType("REAL");

                    b.HasKey("Name");

                    b.ToTable("DataSourceStatus", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Collect.SyncCursor", b =>
                {
                    b.Property<string>("Dataset")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Dataset", "Code");

                    b.ToTable("SyncCursor", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Collect.TradingDay", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.HasKey("Date");

                    b.ToTable("TradingDay", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Equity.HolderCount", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AvgHoldNum")
                        .HasColumnType("REAL");

                    b.Property<double?>("AvgMarketCap")
                        .HasColumnType("REAL");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("HolderNum")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HolderNumChange")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("HolderNumRatio")
                        .HasColumnType("REAL");

                    b.Property<string>("NoticeDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreviousHolderNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportName")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double?>("TotalMarketCap")
                        .HasColumnType("REAL");

                    b.Property<double?>("TotalShares")
                        .HasColumnType("REAL");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code", "EndDate");

                    b.ToTable("HolderCount", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Equity.PledgeStat", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PledgeDealNum")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PledgeMarketCapWan")
                        .HasColumnType("REAL");

                    b.Property<double?>("PledgeRatio")
                        .HasColumnType("REAL");

                    b.Property<double?>("PledgeSharesWan")
                        .HasColumnType("REAL");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Year1ChangePercent")
                        .HasColumnType("REAL");

                    b.HasKey("Code", "TradeDate");

                    b.ToTable("PledgeStat", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Equity.TopHolder", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFreeFloat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("FreeHoldRatio")
                        .HasColumnType("REAL");

                    b.Property<string>("HoldChange")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double>("HoldNum")
                        .HasColumnType("REAL");

                    b.Property<double?>("HoldRatio")
                        .HasColumnType("REAL");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("HolderType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double?>("MarketCap")
                        .HasColumnType("REAL");

                    b.Property<string>("NoticeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SharesType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code", "EndDate", "IsFreeFloat", "Rank");

                    b.ToTable("TopHolder", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Events.EventAnnotation", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventKey")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("Impact")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tone")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Code", "EventKey");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("EventAnnotation", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Finance.EarningsForecast", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Caliber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double?>("ChangeMax")
                        .HasColumnType("REAL");

                    b.Property<double?>("ChangeMin")
                        .HasColumnType("REAL");

                    b.Property<string>("ForecastType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double?>("NetProfitMax")
                        .HasColumnType("REAL");

                    b.Property<double?>("NetProfitMin")
                        .HasColumnType("REAL");

                    b.Property<string>("NoticeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code", "ReportDate");

                    b.ToTable("EarningsForecast", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Finance.FinancialReport", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Bps")
                        .HasColumnType("REAL");

                    b.Property<double?>("DeductedEps")
                        .HasColumnType("REAL");

                    b.Property<string>("DividendPlan")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double?>("DividendYield")
                        .HasColumnType("REAL");

                    b.Property<double?>("Eps")
                        .HasColumnType("REAL");

                    b.Property<double?>("GrossMargin")
                        .HasColumnType("REAL");

                    b.Property<string>("Industry")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double?>("NetProfit")
                        .HasColumnType("REAL");

                    b.Property<double?>("NetProfitQoq")
                        .HasColumnType("REAL");

                    b.Property<double?>("NetProfitYoy")
                        .HasColumnType("REAL");

                    b.Property<string>("NoticeDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OperatingCashFlowPerShare")
                        .HasColumnType("REAL");

                    b.Property<string>("Quarter")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Revenue")
                        .HasColumnType("REAL");

                    b.Property<double?>("RevenueQoq")
                        .HasColumnType("REAL");

                    b.Property<double?>("RevenueYoy")
                        .HasColumnType("REAL");

                    b.Property<double?>("Roe")
                        .HasColumnType("REAL");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code", "ReportDate");

                    b.ToTable("FinancialReport", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.FunctionPointRow", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("FunctionPoint", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.LoginLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Device")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("LoginLog", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.PasswordHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("PasswordIterations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("PasswordHistory", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Device")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiresAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.RoleFunctionPoint", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FunctionPointCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId", "FunctionPointCode");

                    b.ToTable("RoleFunctionPoint", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.RoleQuota", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuotaKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuotaValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId", "QuotaKey");

                    b.ToTable("RoleQuota", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FailCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastLoginIp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LockedUntil")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePwd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("PasswordIterations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TotpEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TotpSecret")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Market.IndexQuote", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("AsOf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Change")
                        .HasColumnType("REAL");

                    b.Property<bool>("Displayed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Market")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double>("Pct")
                        .HasColumnType("REAL");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Volume")
                        .HasColumnType("REAL");

                    b.HasKey("Code");

                    b.ToTable("IndexQuote", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Market.Instrument", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Board")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Market")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pinyin")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedOn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.HasIndex("Industry");

                    b.HasIndex("Name");

                    b.HasIndex("Pinyin");

                    b.ToTable("Instrument", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Market.MarketStat", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("FinanceBalance")
                        .HasColumnType("REAL");

                    b.Property<string>("FundFlowDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Large")
                        .HasColumnType("REAL");

                    b.Property<int>("LimitDown")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LimitUp")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LoanBalance")
                        .HasColumnType("REAL");

                    b.Property<double>("MainNet")
                        .HasColumnType("REAL");

                    b.Property<string>("MarginDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Medium")
                        .HasColumnType("REAL");

                    b.Property<double>("Small")
                        .HasColumnType("REAL");

                    b.Property<double>("SuperLarge")
                        .HasColumnType("REAL");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Date");

                    b.ToTable("MarketStat", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Market.QuoteSnapshot", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("AsOf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Change")
                        .HasColumnType("REAL");

                    b.Property<double>("FloatCap")
                        .HasColumnType("REAL");

                    b.Property<double>("High")
                        .HasColumnType("REAL");

                    b.Property<double>("Low")
                        .HasColumnType("REAL");

                    b.Property<double>("MarketCap")
                        .HasColumnType("REAL");

                    b.Property<double>("Open")
                        .HasColumnType("REAL");

                    b.Property<double>("Pb")
                        .HasColumnType("REAL");

                    b.Property<double>("Pct")
                        .HasColumnType("REAL");

                    b.Property<double>("Pe")
                        .HasColumnType("REAL");

                    b.Property<double>("PeTtm")
                        .HasColumnType("REAL");

                    b.Property<double>("PrevClose")
                        .HasColumnType("REAL");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double>("Turnover")
                        .HasColumnType("REAL");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("VolRatio")
                        .HasColumnType("REAL");

                    b.Property<double>("Volume")
                        .HasColumnType("REAL");

                    b.HasKey("Code");

                    b.HasIndex("Amount");

                    b.HasIndex("Pct");

                    b.ToTable("QuoteSnapshot", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Market.Sector", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("AsOf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DownCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeaderCode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaderName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double>("MainNet")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double>("Pct")
                        .HasColumnType("REAL");

                    b.Property<double>("Pe")
                        .HasColumnType("REAL");

                    b.Property<int>("UpCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.HasIndex("Pct");

                    b.ToTable("Sector", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Rating.RatingConsensus", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("AddNum")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AimPriceMax")
                        .HasColumnType("REAL");

                    b.Property<double?>("AimPriceMin")
                        .HasColumnType("REAL");

                    b.Property<int>("BuyNum")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Eps1")
                        .HasColumnType("REAL");

                    b.Property<double?>("Eps2")
                        .HasColumnType("REAL");

                    b.Property<double?>("Eps3")
                        .HasColumnType("REAL");

                    b.Property<double?>("Eps4")
                        .HasColumnType("REAL");

                    b.Property<string>("IndustryBoard")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LongTermNum")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NeutralNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RatingOrgNum")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReduceNum")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SaleNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year2")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year3")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year4")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YearMark1")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("YearMark2")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("YearMark3")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("YearMark4")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("RatingConsensus", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.System.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSetting", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.System.ExportLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dataset")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ExportLog", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.System.QuotaUsage", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Day")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Used")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "Day", "Kind");

                    b.ToTable("QuotaUsage", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.System.UserSetting", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserSetting", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Watchlist.WatchGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SortOrder");

                    b.ToTable("WatchGroup", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Watchlist.WatchItem", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("AddedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "Code");

                    b.HasIndex("GroupId");

                    b.ToTable("WatchItem", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Alerts.AlertRule", b =>
                {
                    b.HasOne("SA.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SA.Domain.Entities.Alerts.Notification", b =>
                {
                    b.HasOne("SA.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.PasswordHistory", b =>
                {
                    b.HasOne("SA.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.HasOne("SA.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.RoleFunctionPoint", b =>
                {
                    b.HasOne("SA.Domain.Entities.Identity.Role", null)
                        .WithMany("FunctionPoints")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.RoleQuota", b =>
                {
                    b.HasOne("SA.Domain.Entities.Identity.Role", null)
                        .WithMany("Quotas")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.User", b =>
                {
                    b.HasOne("SA.Domain.Entities.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SA.Domain.Entities.System.ExportLog", b =>
                {
                    b.HasOne("SA.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SA.Domain.Entities.System.QuotaUsage", b =>
                {
                    b.HasOne("SA.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SA.Domain.Entities.System.UserSetting", b =>
                {
                    b.HasOne("SA.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SA.Domain.Entities.Watchlist.WatchGroup", b =>
                {
                    b.HasOne("SA.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SA.Domain.Entities.Watchlist.WatchItem", b =>
                {
                    b.HasOne("SA.Domain.Entities.Watchlist.WatchGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SA.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.Role", b =>
                {
                    b.Navigation("FunctionPoints");

                    b.Navigation("Quotas");
                });
#pragma warning restore 612, 618
        }
    }
}
