// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SA.Infrastructure.Persistence;

#nullable disable

namespace SA.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SaDbContext))]
    partial class SaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("SA.Domain.Entities.Identity.FunctionPointRow", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("FunctionPoint", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.LoginLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Device")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("LoginLog", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.PasswordHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("PasswordIterations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("PasswordHistory", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Device")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiresAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.RoleFunctionPoint", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FunctionPointCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId", "FunctionPointCode");

                    b.ToTable("RoleFunctionPoint", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.RoleQuota", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuotaKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuotaValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId", "QuotaKey");

                    b.ToTable("RoleQuota", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FailCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastLoginIp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LockedUntil")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePwd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("PasswordIterations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TotpEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TotpSecret")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.System.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSetting", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.System.ExportLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dataset")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ExportLog", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.System.QuotaUsage", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Day")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Used")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "Day", "Kind");

                    b.ToTable("QuotaUsage", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.System.UserSetting", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserSetting", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.PasswordHistory", b =>
                {
                    b.HasOne("SA.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.HasOne("SA.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.RoleFunctionPoint", b =>
                {
                    b.HasOne("SA.Domain.Entities.Identity.Role", null)
                        .WithMany("FunctionPoints")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.RoleQuota", b =>
                {
                    b.HasOne("SA.Domain.Entities.Identity.Role", null)
                        .WithMany("Quotas")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.User", b =>
                {
                    b.HasOne("SA.Domain.Entities.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SA.Domain.Entities.System.ExportLog", b =>
                {
                    b.HasOne("SA.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SA.Domain.Entities.System.QuotaUsage", b =>
                {
                    b.HasOne("SA.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SA.Domain.Entities.System.UserSetting", b =>
                {
                    b.HasOne("SA.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SA.Domain.Entities.Identity.Role", b =>
                {
                    b.Navigation("FunctionPoints");

                    b.Navigation("Quotas");
                });
#pragma warning restore 612, 618
        }
    }
}
